export interface PaintProduct {
  name: string
  code: string
  resin: string
  type: string
  base: string
  volumeSolidsPct: number | null
  recommendedMicrons: number | null
  minMicrons: number | null
  maxMicrons: number | null
  application: string
}

/**
 * Hempel Protective coatings assortment, sourced from Clin Corp's
 * 'Assortment Library_English.xlsx' (sheet: Protective). volumeSolidsPct
 * and recommendedMicrons feed the coverage formula in calculations.ts;
 * products missing either value (2 of 101) are technical-data-only and
 * excluded from litres calculations.
 */
export const PAINT_PRODUCTS: PaintProduct[] = [
  {
    "name": "Hempel's Uniprimer",
    "code": "13140",
    "resin": "Alkyd",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 42,
    "recommendedMicrons": 50,
    "minMicrons": 25,
    "maxMicrons": 80,
    "application": "Maintenance"
  },
  {
    "name": "Hempel's Speed dry primer",
    "code": "13770",
    "resin": "Alkyd",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 57,
    "recommendedMicrons": 40,
    "minMicrons": 40,
    "maxMicrons": 80,
    "application": "Standar quality - Cheap for medium and low corrosion environments"
  },
  {
    "name": "Hemucryl primer Hi-Build",
    "code": "18032",
    "resin": "Acrylic",
    "type": "Primer",
    "base": "Water",
    "volumeSolidsPct": 43,
    "recommendedMicrons": 75,
    "minMicrons": 50,
    "maxMicrons": 100,
    "application": "Interior and exterior of low/medium corrosion environments, galvanized steel, aluminum and stainless steel"
  },
  {
    "name": "Hempadur",
    "code": "15570",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 54,
    "recommendedMicrons": 100,
    "minMicrons": 50,
    "maxMicrons": 125,
    "application": "Standard, maintenance in highly corrosive environments"
  },
  {
    "name": "Hempadur",
    "code": "15590",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 44,
    "recommendedMicrons": 40,
    "minMicrons": 30,
    "maxMicrons": 50,
    "application": "Primer for highly corrosive environments subjected to high abrasion"
  },
  {
    "name": "Hempadur",
    "code": "15553",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 55,
    "recommendedMicrons": 50,
    "minMicrons": 50,
    "maxMicrons": 80,
    "application": "Galvanized Steel (International), Aluminum & Stainless Steel, Medium/Strong Corrosive Environments"
  },
  {
    "name": "Hempel's Epoxy primer H.V.",
    "code": "15410",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 48,
    "recommendedMicrons": 50,
    "minMicrons": 50,
    "maxMicrons": 80,
    "application": "For galvanized steel (In Spain). Can also be used on steel and other surfaces"
  },
  {
    "name": "Hempadur",
    "code": "15552",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 42,
    "recommendedMicrons": 40,
    "minMicrons": 30,
    "maxMicrons": 50,
    "application": ""
  },
  {
    "name": "Hempadur",
    "code": "17410",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 74,
    "recommendedMicrons": 100,
    "minMicrons": 70,
    "maxMicrons": 125,
    "application": "Generic quick-drying primer with zinc phosphate."
  },
  {
    "name": "Hempadur Speed Dry ZP 500",
    "code": "17500",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 125,
    "minMicrons": 70,
    "maxMicrons": 150,
    "application": "New build construction onshore with short repainting intervals, chemical plants, stadiums, showrooms"
  },
  {
    "name": "Hempadur Speed Dry ZP 650",
    "code": "17650",
    "resin": "Epoxy",
    "type": "Primer",
    "base": "Solvent",
    "volumeSolidsPct": 66,
    "recommendedMicrons": 120,
    "minMicrons": 75,
    "maxMicrons": 200,
    "application": "Fast refinish intervals and no optimal surface, special ACQPA C4"
  },
  {
    "name": "Hempel Silicone Acrylic",
    "code": "56940",
    "resin": "Acrylic silicone",
    "type": "Heat Resistant",
    "base": "Solvent",
    "volumeSolidsPct": 54,
    "recommendedMicrons": 25,
    "minMicrons": 25,
    "maxMicrons": 50,
    "application": "High temperature pipes (Up to 400C aluminum color)"
  },
  {
    "name": "Hempel Silicone Aluminium",
    "code": "56914",
    "resin": "Silicone aluminium",
    "type": "Heat Resistant",
    "base": "Solvent",
    "volumeSolidsPct": 43,
    "recommendedMicrons": 25,
    "minMicrons": 20,
    "maxMicrons": 40,
    "application": "Very high temperature pipes (Up to 600C)"
  },
  {
    "name": "Hempaprime CUI 275",
    "code": "17530",
    "resin": "Epoxy",
    "type": "Heat Resistant",
    "base": "Solvent",
    "volumeSolidsPct": 66,
    "recommendedMicrons": 150,
    "minMicrons": 100,
    "maxMicrons": 225,
    "application": "CUI - Systems under insulation up to 200 ºC"
  },
  {
    "name": "Versiline CUI 56990",
    "code": "56990",
    "resin": "PMMA",
    "type": "Heat Resistant",
    "base": "Solvent",
    "volumeSolidsPct": 74,
    "recommendedMicrons": 150,
    "minMicrons": 150,
    "maxMicrons": 225,
    "application": "Systems under insulation (up to 650 C)"
  },
  {
    "name": "Hempel's Silvium",
    "code": "51570",
    "resin": "Oleoresin",
    "type": "Heat Resistant",
    "base": "Solvent",
    "volumeSolidsPct": 38,
    "recommendedMicrons": 25,
    "minMicrons": 25,
    "maxMicrons": 25,
    "application": "Hot pipes or chimneys at a permanent high T, with good light reflection required, medium corrosive environments."
  },
  {
    "name": "Hempadur Avantguard 860",
    "code": "17990",
    "resin": "Epoxy",
    "type": "Zinc",
    "base": "Solvent",
    "volumeSolidsPct": 66,
    "recommendedMicrons": 60,
    "minMicrons": 40,
    "maxMicrons": 100,
    "application": "Highly corrosive environments, oil & gas, energy, infrastructure, marine environments (85% Zn)"
  },
  {
    "name": "Hempadur Avantguard 770",
    "code": "17382",
    "resin": "Epoxy",
    "type": "Zinc",
    "base": "Solvent",
    "volumeSolidsPct": 66,
    "recommendedMicrons": 60,
    "minMicrons": 40,
    "maxMicrons": 90,
    "application": "Non-AVG Highly Corrosive Environments, Marine Environments (80% Zn)"
  },
  {
    "name": "Hempadur Avantguard 750",
    "code": "1736G",
    "resin": "Epoxy",
    "type": "Zinc",
    "base": "Solvent",
    "volumeSolidsPct": 65,
    "recommendedMicrons": 60,
    "minMicrons": 40,
    "maxMicrons": 100,
    "application": "Highly corrosive environments (80% Zn)"
  },
  {
    "name": "Hempadur Avantguard 550",
    "code": "1734G",
    "resin": "Epoxy",
    "type": "Zinc",
    "base": "Solvent",
    "volumeSolidsPct": 65,
    "recommendedMicrons": 60,
    "minMicrons": 40,
    "maxMicrons": 100,
    "application": "Highly corrosive environments (65% Zn)"
  },
  {
    "name": "Hempadur Pro Zinc",
    "code": "17380",
    "resin": "Epoxy",
    "type": "Zinc",
    "base": "Solvent",
    "volumeSolidsPct": 60,
    "recommendedMicrons": 60,
    "minMicrons": 50,
    "maxMicrons": 75,
    "application": "Highly corrosive environments (80% Zn) non-Avg special for ACQPA-C5"
  },
  {
    "name": "Hempel's Galvosil",
    "code": "15700",
    "resin": "Silicate",
    "type": "Zinc",
    "base": "Solvent",
    "volumeSolidsPct": 64,
    "recommendedMicrons": 50,
    "minMicrons": 50,
    "maxMicrons": 125,
    "application": "Medium/strong corrosion environments subjected to abrasion. Inside Tanks"
  },
  {
    "name": "Hempel's Galvosil E",
    "code": "15BES",
    "resin": "Silicate",
    "type": "Zinc",
    "base": "Solvent",
    "volumeSolidsPct": 65,
    "recommendedMicrons": 75,
    "minMicrons": 75,
    "maxMicrons": 75,
    "application": "Medium/strong corrosion environments subjected to abrasion. Inside tanks. For UNE Standard"
  },
  {
    "name": "Hempel's Shopprimer ZS",
    "code": "15890",
    "resin": "Silicate",
    "type": "Shopprimer",
    "base": "Solvent",
    "volumeSolidsPct": 28,
    "recommendedMicrons": 15,
    "minMicrons": 10,
    "maxMicrons": 25,
    "application": "Temporary protection with Zinc"
  },
  {
    "name": "Hempel's Shopprimer E",
    "code": "15275",
    "resin": "Epoxy",
    "type": "Shopprimer",
    "base": "Solvent",
    "volumeSolidsPct": 26,
    "recommendedMicrons": 20,
    "minMicrons": 15,
    "maxMicrons": 25,
    "application": "Temporary protection standard"
  },
  {
    "name": "Hempaprime Multi 500 Summer",
    "code": "45950",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 85,
    "recommendedMicrons": 150,
    "minMicrons": 100,
    "maxMicrons": 225,
    "application": "Global standard for short refinish times and high productivity"
  },
  {
    "name": "Hempaprime Multi 500 Winter",
    "code": "45953",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 85,
    "recommendedMicrons": 150,
    "minMicrons": 100,
    "maxMicrons": 225,
    "application": "Global standard for short refinish times and high productivity"
  },
  {
    "name": "Hempadur",
    "code": "47200",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 65,
    "recommendedMicrons": 100,
    "minMicrons": 75,
    "maxMicrons": 200,
    "application": "Designed for short refinishes, special for ACQPA C4."
  },
  {
    "name": "Hempadur",
    "code": "47300",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 83,
    "recommendedMicrons": 200,
    "minMicrons": 100,
    "maxMicrons": 250,
    "application": "Atmospheric exposure, severe corrosion environments with abrasion and seawater, short repainting times"
  },
  {
    "name": "Hempadur",
    "code": "4774D",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 76,
    "recommendedMicrons": 150,
    "minMicrons": 100,
    "maxMicrons": 250,
    "application": "Only for Wind."
  },
  {
    "name": "Hempadur Mastic",
    "code": "45880",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 80,
    "recommendedMicrons": 125,
    "minMicrons": 100,
    "maxMicrons": 200,
    "application": "Maintenance. High thicknesses and wide repainting intervals. Surfaces not optimally prepared. High thicknesses"
  },
  {
    "name": "Hempadur Mastic",
    "code": "45881",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 80,
    "recommendedMicrons": 125,
    "minMicrons": 100,
    "maxMicrons": 200,
    "application": "High temperatures (>30ºC): Maintenance. long repainting times. Surfaces not optimally prepared. High thicknesses"
  },
  {
    "name": "Hempadur Mastic",
    "code": "4588W",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 80,
    "recommendedMicrons": 200,
    "minMicrons": 100,
    "maxMicrons": 200,
    "application": "For low temperatures (Up to -10ºC). Atmospheric exposure systems. High thicknesses."
  },
  {
    "name": "Hempadur Mastic",
    "code": "45890",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 77,
    "recommendedMicrons": 200,
    "minMicrons": 150,
    "maxMicrons": 250,
    "application": "For cases where low VOCs and extended refinish intervals are required"
  },
  {
    "name": "Hempadur Mastic",
    "code": "8588E",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 125,
    "minMicrons": 125,
    "maxMicrons": 200,
    "application": "Multi-surface primer, special ACQPA C5"
  },
  {
    "name": "Hempadur Fast Dry",
    "code": "45410",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 65,
    "recommendedMicrons": 80,
    "minMicrons": 80,
    "maxMicrons": 125,
    "application": "Low or high corrosion environments (low if it is monolayer). When aesthetics are not important"
  },
  {
    "name": "Hempadur",
    "code": "45141",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 60,
    "recommendedMicrons": 150,
    "minMicrons": 125,
    "maxMicrons": 175,
    "application": "When high adhesion is needed. Marine repairs, in warm climates"
  },
  {
    "name": "Hempadur",
    "code": "45143",
    "resin": "Epoxy",
    "type": "Intermediate",
    "base": "Solvent",
    "volumeSolidsPct": 60,
    "recommendedMicrons": 150,
    "minMicrons": 80,
    "maxMicrons": 175,
    "application": "When high adhesion is needed. Marine repairs, in cold climates"
  },
  {
    "name": "Hempadur Multistrength GF",
    "code": "35870",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "Solvent",
    "volumeSolidsPct": 87,
    "recommendedMicrons": 350,
    "minMicrons": 300,
    "maxMicrons": 500,
    "application": "Areas subject to abrasion in highly corrosive environments, for submerged systems or splash zones. For grain loads (Marine)"
  },
  {
    "name": "Hempadur Multistrength",
    "code": "35840",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 500,
    "minMicrons": 250,
    "maxMicrons": 1000,
    "application": "Highly corrosive environments, splash zone and diving areas (Protective offshore). More fiber concentration"
  },
  {
    "name": "Hempadur Multistrength",
    "code": "35842",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "SF",
    "volumeSolidsPct": 98,
    "recommendedMicrons": 750,
    "minMicrons": 500,
    "maxMicrons": 1000,
    "application": "Highly corrosive environments, splash zone and submerged areas when you need more thickness"
  },
  {
    "name": "Hempadur EM",
    "code": "35740",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "SF",
    "volumeSolidsPct": 97,
    "recommendedMicrons": 150,
    "minMicrons": 150,
    "maxMicrons": 400,
    "application": "For patching with very poor surface preparation, maintenance."
  },
  {
    "name": "Hempadur Multistrength",
    "code": "45753",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "Solvent",
    "volumeSolidsPct": 79,
    "recommendedMicrons": 200,
    "minMicrons": 150,
    "maxMicrons": 300,
    "application": "Highly corrosive and immersed environments, splash zone as a finishing coat (Various colors)"
  },
  {
    "name": "Hempadur Multistrength",
    "code": "45703",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "Solvent",
    "volumeSolidsPct": 70,
    "recommendedMicrons": 200,
    "minMicrons": 150,
    "maxMicrons": 300,
    "application": "Highly corrosive and submerged environments, with aluminum splash zone"
  },
  {
    "name": "Hempadur Sprayguard",
    "code": "35490",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 2500,
    "minMicrons": 2500,
    "maxMicrons": null,
    "application": "Severe corrosion and impact conditions, splash zones with very high thicknesses"
  },
  {
    "name": "Hempadur Sprayguard",
    "code": "35493",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 2500,
    "minMicrons": 2500,
    "maxMicrons": null,
    "application": "Severe corrosion and impact conditions, splash zones when more productivity is needed (Winter)"
  },
  {
    "name": "Hempaprime Strength 530",
    "code": "45500",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "Solvent",
    "volumeSolidsPct": 90,
    "recommendedMicrons": 500,
    "minMicrons": 175,
    "maxMicrons": 750,
    "application": "Immersion and splash zones, reinforced with glass (3 versions)"
  },
  {
    "name": "Hempadur Quattro XO",
    "code": "17870",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "Solvent",
    "volumeSolidsPct": 80,
    "recommendedMicrons": 125,
    "minMicrons": 100,
    "maxMicrons": 250,
    "application": "Atmospheric exposure and water (Permanent immersion). Ballast tanks"
  },
  {
    "name": "Hempadur Quattro",
    "code": "17634",
    "resin": "Epoxy",
    "type": "Abrasion resistance",
    "base": "Solvent",
    "volumeSolidsPct": 72,
    "recommendedMicrons": 125,
    "minMicrons": 100,
    "maxMicrons": 200,
    "application": "Permanent or Outdoor Immersion (Marine Primer)"
  },
  {
    "name": "Hempadur",
    "code": "35620",
    "resin": "Epoxy",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 200,
    "minMicrons": 200,
    "maxMicrons": 400,
    "application": "Standard 100% solid without GF. Drinking water tanks and pipes. (Not in Spain)"
  },
  {
    "name": "Hempadur",
    "code": "85671",
    "resin": "Novolac",
    "type": "Tank Coatings",
    "base": "Solvent",
    "volumeSolidsPct": 68,
    "recommendedMicrons": 100,
    "minMicrons": 90,
    "maxMicrons": 160,
    "application": "Inside tanks, pipes, water (23ºC) etc. chemical resistance with higher temperatures"
  },
  {
    "name": "Hempadur",
    "code": "35760",
    "resin": "Phenolic",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 300,
    "minMicrons": 250,
    "maxMicrons": 600,
    "application": "Tank interior, can be used in combination with GF"
  },
  {
    "name": "Hempadur",
    "code": "35560",
    "resin": "Epoxy",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 200,
    "minMicrons": 200,
    "maxMicrons": 600,
    "application": "For drinking water tanks and pipes (Up to 23ºC, In Spain). Splash zones. Liquid only - limited dry product"
  },
  {
    "name": "Hempaline Defend 400 Cure 72",
    "code": "37810",
    "resin": "Epoxy",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 500,
    "minMicrons": 300,
    "maxMicrons": 750,
    "application": "Interior of tanks and pipes with chemicals and petrochemicals (fuels) for rapid commissioning. Can be applied in combination with GF"
  },
  {
    "name": "Hempaline Defend 400 Cure 24",
    "code": "37811",
    "resin": "Epoxy",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 500,
    "minMicrons": 300,
    "maxMicrons": 750,
    "application": "Interior of tanks and pipes with chemicals and petrochemicals (fuels) for very fast commissioning. Can be applied in combination with GF"
  },
  {
    "name": "Hempadur",
    "code": "87540",
    "resin": "Phenolic",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 625,
    "minMicrons": 500,
    "maxMicrons": 1500,
    "application": "Exterior of buried pipes or valves"
  },
  {
    "name": "Hempaline Defend 630 Cure 72",
    "code": "37820",
    "resin": "Novolac",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 500,
    "minMicrons": 300,
    "maxMicrons": 750,
    "application": "Interior of tanks and pipes with chemicals and petrochemicals (fuels). Can be applied in combination with GF"
  },
  {
    "name": "Hempaline Defend 630 Cure 24",
    "code": "37821",
    "resin": "Novolac",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 500,
    "minMicrons": 300,
    "maxMicrons": 750,
    "application": "Interior of tanks and pipes with chemicals and petrochemicals (fuels). It can be applied in combination with GF. Faster curing"
  },
  {
    "name": "Hempaline Defend 640 Cure 72",
    "code": "37830",
    "resin": "Novolac",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 500,
    "minMicrons": 300,
    "maxMicrons": 750,
    "application": "Inside tanks and pipes with built-in GF chemicals, for tank repairs with severe pitting"
  },
  {
    "name": "Hempaline Defend 740",
    "code": "35910",
    "resin": "Vinil Ester",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 650,
    "minMicrons": 500,
    "maxMicrons": 750,
    "application": "For Acid Storage"
  },
  {
    "name": "Hempaline Prepare 110",
    "code": "07810",
    "resin": "Epoxy",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 150,
    "minMicrons": 150,
    "maxMicrons": 200,
    "application": "Preparation of concrete for subsequent application of the defenders"
  },
  {
    "name": "Hempaline Prepare 120",
    "code": "17040",
    "resin": "Vinil Ester",
    "type": "Tank Coatings",
    "base": "",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 100,
    "minMicrons": 75,
    "maxMicrons": 200,
    "application": ""
  },
  {
    "name": "Hempaline Prepare 130",
    "code": "17100",
    "resin": "",
    "type": "Tank Coatings",
    "base": "",
    "volumeSolidsPct": null,
    "recommendedMicrons": null,
    "minMicrons": null,
    "maxMicrons": null,
    "application": ""
  },
  {
    "name": "Hempathane PW",
    "code": "35660",
    "resin": "Polyurethane",
    "type": "Tank Coatings",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": 500,
    "minMicrons": 300,
    "maxMicrons": 2000,
    "application": "Pipes and drinking water tanks when very fast curing is required (Not in Spain). Other Types of Pipes"
  },
  {
    "name": "Hempel's HS Gas Pipe Coatings",
    "code": "87831",
    "resin": "Epoxy",
    "type": "Tank Coatings",
    "base": "Solvent",
    "volumeSolidsPct": 82,
    "recommendedMicrons": 80,
    "minMicrons": 80,
    "maxMicrons": 80,
    "application": "For dry and sweet gas pipes"
  },
  {
    "name": "Hempadur",
    "code": "15600",
    "resin": "Epoxy",
    "type": "Tank Coatings",
    "base": "Solvent",
    "volumeSolidsPct": 77,
    "recommendedMicrons": 160,
    "minMicrons": 100,
    "maxMicrons": 200,
    "application": "Standard of Tanks and Pipes for Oil and Other Aggressive Products (Brine, Fish, etc.)"
  },
  {
    "name": "Hempadur",
    "code": "15500",
    "resin": "Novolac",
    "type": "Tank Coatings",
    "base": "Solvent",
    "volumeSolidsPct": 68,
    "recommendedMicrons": 100,
    "minMicrons": 90,
    "maxMicrons": 160,
    "application": "New Tank Interior"
  },
  {
    "name": "Hempafire Pro 400",
    "code": "43490",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent designed for up to C4 and 90 mins for cellulosic fire"
  },
  {
    "name": "Hempafire Pro 400 Fast Dry",
    "code": "43491",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent designed for up to C4 and 90 mins for cellulosic fire. For application in cold environments"
  },
  {
    "name": "Hempafire Pro 315",
    "code": "43360",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent designed for up to C4 and 60 mins for cellulosic fire"
  },
  {
    "name": "Hempafire Pro 315 Fast Dry",
    "code": "43361",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent designed for up to C4 and 60 mins for cellulosic fire. For application in cold environments"
  },
  {
    "name": "Hempafire Pro 320",
    "code": "43320",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent designed for up to C4 and 60 mins for cellulosic fire. More competitive with low massiveness"
  },
  {
    "name": "Hempafire Pro 320 Fast Dry",
    "code": "43321",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent designed for up to C4 and 60 mins for cellulosic fire. To be applied in cold environments. More competitive with low massiveness"
  },
  {
    "name": "Hempacore One",
    "code": "43600",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent for environments up to C4 and 120 mins"
  },
  {
    "name": "Hempacore One FD",
    "code": "43601",
    "resin": "Acrylic",
    "type": "Intumescent",
    "base": "Solvent",
    "volumeSolidsPct": 75,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent for environments up to C4 and 120 mins To apply in cold environments"
  },
  {
    "name": "Hempacore AQ",
    "code": "48860",
    "resin": "Intumescent",
    "type": "Intumescent",
    "base": "Water",
    "volumeSolidsPct": 67,
    "recommendedMicrons": 750,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Water-based intumescent for low corrosive environments (C2)"
  },
  {
    "name": "Hempafire XTR 100",
    "code": "67820",
    "resin": "Intumescent",
    "type": "Intumescent",
    "base": "SF",
    "volumeSolidsPct": 100,
    "recommendedMicrons": null,
    "minMicrons": null,
    "maxMicrons": null,
    "application": "Intumescent Hydrocarbons, Pool and Jet Fire UL 1709 certified"
  },
  {
    "name": "Hempathane Topcoat",
    "code": "55210",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 51,
    "recommendedMicrons": 50,
    "minMicrons": 40,
    "maxMicrons": 80,
    "application": "Standard finish for high quality in high or very high corrosion environments"
  },
  {
    "name": "Hempathane Topcoat",
    "code": "55213",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 49,
    "recommendedMicrons": 50,
    "minMicrons": 40,
    "maxMicrons": 80,
    "application": "Finish for high and very high corrosion conditions where color retention is needed and not as much gloss"
  },
  {
    "name": "Hempathane HS",
    "code": "55610",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 67,
    "recommendedMicrons": 100,
    "minMicrons": 50,
    "maxMicrons": 125,
    "application": "High solids finish for high or very high corrosion environments, monolayer in C2 and C3"
  },
  {
    "name": "Hempathane HS",
    "code": "5561B",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 61,
    "recommendedMicrons": 75,
    "minMicrons": 50,
    "maxMicrons": 75,
    "application": "High solids finish for fast-drying high- or ultra-high-corrosion environments"
  },
  {
    "name": "Hempathane HS",
    "code": "55613",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 57,
    "recommendedMicrons": 100,
    "minMicrons": 75,
    "maxMicrons": 125,
    "application": "Acabado de altos solidos para ambientes de alta o muy alta corrosión, monocapa en C2 y C3 donde se necesite retencion de color"
  },
  {
    "name": "Hempel's Polyenamel",
    "code": "55102",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 52,
    "recommendedMicrons": 35,
    "minMicrons": 30,
    "maxMicrons": 40,
    "application": "High solids finish for high or very high corrosion environments, monocoat in C2 and C3 where color retention is needed"
  },
  {
    "name": "Hempathane",
    "code": "55930",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 58,
    "recommendedMicrons": 50,
    "minMicrons": 30,
    "maxMicrons": 60,
    "application": "Very high quality and high gloss for high corrosion environments"
  },
  {
    "name": "Hempathane Speed Dry Topcoat 250",
    "code": "55250",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 62,
    "recommendedMicrons": 50,
    "minMicrons": 50,
    "maxMicrons": 120,
    "application": "Fast-drying standard quality with high solids"
  },
  {
    "name": "Hempathane Fast Dry",
    "code": "55750",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 65,
    "recommendedMicrons": 100,
    "minMicrons": 60,
    "maxMicrons": 160,
    "application": "Quick-drying standard with various colors. Documented for C3-H in monolayer (Cheaper high solids)"
  },
  {
    "name": "Hempel's Pro Acrylic",
    "code": "55883",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 58,
    "recommendedMicrons": 50,
    "minMicrons": 50,
    "maxMicrons": 100,
    "application": "When light resistance and brightness are needed in highly corrosive environments. It is widely used in Nordic countries where isocyanate (PU) is banned,"
  },
  {
    "name": "Hempaxane Classic",
    "code": "55000",
    "resin": "Polysiloxane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 85,
    "recommendedMicrons": 125,
    "minMicrons": 100,
    "maxMicrons": 125,
    "application": "Isocyanate-free finish for high corrosion"
  },
  {
    "name": "Hempaxane Light",
    "code": "55030",
    "resin": "Polysiloxane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 82,
    "recommendedMicrons": 75,
    "minMicrons": 50,
    "maxMicrons": 80,
    "application": "Multi-color isocyanate-free finish for high corrosion"
  },
  {
    "name": "Hempel Speed Dry Alkyd",
    "code": "43140",
    "resin": "Alkyd",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 49,
    "recommendedMicrons": 60,
    "minMicrons": 40,
    "maxMicrons": 120,
    "application": "Structures, Industry (Monolayer possible) with fast drying, interiors and exteriors with low/medium corrosion"
  },
  {
    "name": "Hempel Speed Dry Alkyd",
    "code": "43141",
    "resin": "Alkyd",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 48,
    "recommendedMicrons": 80,
    "minMicrons": 60,
    "maxMicrons": 120,
    "application": "Structures, Industry (Possible monolayer) with fast drying, interiors and exteriors with low/medium corrosion. When a Glossier Finish Is Needed"
  },
  {
    "name": "Hempalin Enamel",
    "code": "52140",
    "resin": "Alkyd",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 46,
    "recommendedMicrons": 30,
    "minMicrons": 25,
    "maxMicrons": 40,
    "application": "Standard in low/medium corrosion systems"
  },
  {
    "name": "Hempaquick",
    "code": "53840",
    "resin": "Alkyd",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 41,
    "recommendedMicrons": 25,
    "minMicrons": 40,
    "maxMicrons": 40,
    "application": "Standard in low/medium corrosion systems with higher gloss and fast drying"
  },
  {
    "name": "Hempatex Hi-Build",
    "code": "46410",
    "resin": "Acrylic",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 42,
    "recommendedMicrons": 100,
    "minMicrons": 50,
    "maxMicrons": 125,
    "application": "Superstructures, ship decks, industry, warehouse exteriors. Quick maintenance work, finishing on containers"
  },
  {
    "name": "Hempatex Enamel",
    "code": "56360",
    "resin": "Acrylic",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 32,
    "recommendedMicrons": 35,
    "minMicrons": 35,
    "maxMicrons": 35,
    "application": "Indoor and outdoor medium/strong aggressive environments"
  },
  {
    "name": "Hemucryl Enamel Hi-build",
    "code": "58030",
    "resin": "Acrylic",
    "type": "Topcoat",
    "base": "Water",
    "volumeSolidsPct": 44,
    "recommendedMicrons": 75,
    "minMicrons": 50,
    "maxMicrons": 100,
    "application": "Superstructures in medium/high corrosion environments, indoors and outdoors"
  },
  {
    "name": "Hemucryl Enamel",
    "code": "58100",
    "resin": "Acrylic",
    "type": "Topcoat",
    "base": "Water",
    "volumeSolidsPct": 41,
    "recommendedMicrons": 30,
    "minMicrons": 30,
    "maxMicrons": 50,
    "application": "Constructions in medium/high corrosion environments, indoors and outdoors"
  },
  {
    "name": "Hemuthane",
    "code": "58510",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Water",
    "volumeSolidsPct": 49,
    "recommendedMicrons": 40,
    "minMicrons": 30,
    "maxMicrons": 60,
    "application": "Water-based polyurethane finish (2 components) for low volatile systems"
  },
  {
    "name": "Hemepl's PU MIO Coat",
    "code": "447E0",
    "resin": "Polyurethane",
    "type": "Topcoat",
    "base": "Solvent",
    "volumeSolidsPct": 54,
    "recommendedMicrons": 70,
    "minMicrons": 60,
    "maxMicrons": 150,
    "application": "Special for high voltage lines (electricity and power). Excellent adherence to galvanized steel"
  },
  {
    "name": "Hemucryl",
    "code": "48120",
    "resin": "Acrylic",
    "type": "Topcoat",
    "base": "Water",
    "volumeSolidsPct": 42,
    "recommendedMicrons": 80,
    "minMicrons": 60,
    "maxMicrons": 120,
    "application": "Finish for water-based systems"
  },
  {
    "name": "Hemudur",
    "code": "48582",
    "resin": "Epoxy",
    "type": "Concrete",
    "base": "Water",
    "volumeSolidsPct": 54,
    "recommendedMicrons": 80,
    "minMicrons": 60,
    "maxMicrons": 120,
    "application": "Water-based finish for concrete (pavements, tunnels, non-slip, etc.)"
  }
]
